### ISSUE TITLE
Discovery Mode not working

### ISSUE THREAD

**Issue by bartremans** [julien6387/supvisors#126]
Hi,

I'm trying to configure discovery mode but the instances don't find each other.

When I ping the multicast address, I get a response of all the multicast enabled hosts:

_PING 224.0.0.251 (224.0.0.251) 56(84) bytes of data.
64 bytes from 10.0.133.59: icmp_seq=1 ttl=64 time=0.040 ms
64 bytes from 10.0.137.183: icmp_seq=1 ttl=64 time=0.501 ms (DUP!)
64 bytes from 10.0.130.195: icmp_seq=1 ttl=64 time=0.533 ms (DUP!)
64 bytes from 10.0.133.59: icmp_seq=2 ttl=64 time=0.049 ms
64 bytes from 10.0.130.195: icmp_seq=2 ttl=64 time=0.346 ms (DUP!)
64 bytes from 10.0.137.183: icmp_seq=2 ttl=64 time=0.376 ms (DUP!)
64 bytes from 10.0.133.59: icmp_seq=3 ttl=64 time=0.052 ms
64 bytes from 10.0.130.195: icmp_seq=3 ttl=64 time=0.354 ms (DUP!)
64 bytes from 10.0.137.183: icmp_seq=3 ttl=64 time=0.379 ms (DUP!)
64 bytes from 10.0.133.59: icmp_seq=4 ttl=64 time=0.047 ms
64 bytes from 10.0.130.195: icmp_seq=4 ttl=64 time=0.338 ms (DUP!)
64 bytes from 10.0.137.183: icmp_seq=4 ttl=64 time=1.13 ms (DUP!)
64 bytes from 10.0.133.59: icmp_seq=5 ttl=64 time=0.043 ms
64 bytes from 10.0.137.183: icmp_seq=5 ttl=64 time=0.333 ms (DUP!)_

My rpcinterface config:

_[rpcinterface:supvisors]
supervisor.rpcinterface_factory = supvisors.plugin:make_supvisors_rpcinterface
internal_port = 60001
event_link = ZMQ
event_port = 60002
rules_files = /home/ubuntu/ES.4/s3-bucket/rules.xml
conciliation_strategy = RESTART
;supvisors_list = ip-10-0-130-195.eu-central-1.compute.internal,ip-10-0-137-183.eu-central-1.compute.internal,ip-10-0-133-59.eu-central-1.compute.internal,
stereotypes = @SERVER
multicast_group = 224.0.0.251:60003
multicast_interface = INADDR_ANY
multicast_ttl = 10
core_identifiers = @SERVER_

But when using discovery mode, all instances declare it is used but they don't find eachother:

_ubuntu@ip-10-0-137-183:~/ES.4/s3-bucket$ supvisorsctl instance_status
Supervisor             Host             Port   State      Discovery  Load  Time      Counter  Processes  FSM             Discovery  Master                 Starting  Stopping
ip-10-0-137-183:60000  ip-10-0-137-183  60000  RUNNING    True       0%    09:14:50  40       error      OPERATION       True       ip-10-0-137-183:60000  False     False_

When using supvisorlist, it is working. 

Where to look? misconfiguration issue?

Kind regards,

Bart

**Comment by julien6387** [comment]
Hi,

I don't see any obvious issue in your Supvisors configuration but I'll try it as soon as I can.
Which version of Supvisors are you using ?

My best guess is that multicast (igmp protocol) is disabled in your firewall configuration (default behaviour).

A few other leads, just in case:
* 60003 is likely in the dynamic port range of the OS, so check if it is not already bound by another process (bad luck) and/or use a port in the registered range of the OS
* check that `netstat -g` shows 224.0.0.251
* try a basic multicast exchange using a tool like iperf.

Kind regards,
Julien.

**Comment by julien6387** [comment]
I've just tested your configuration on my rig (with a different rules file) and it works.
So I definitely suspect a network configuration issue here.

Unless there is a lot of hardware between your nodes, I assume that a TTL=10 is comfortable enough.
I'm not a system admin expert but as far as I can tell:

1) MULTICAST must be activated on the network device
```
    ip link set multicast on dev <network interface>
    ip addr show <network interface>
```

2) the IGMP protocol must be enabled on firewalld
```
    firewall-cmd --zone=zone-name --add-protocol=igmp
```

Depending on your network configuration and hardware, multicast may also be denied by an ACL on a switch.

Cheers,
Julien.

**Comment by bartremans** [comment]
Hi Julien,

Thx for the swift support! I'll check my network configuration. 

Kind regards,

Bart

**Comment by julien6387** [comment]
assumed solved

**Comment by bartremans** [comment]
Hi Julien,

Can you help me with this warning concerning multicast setup:


2024-07-02 08:23:50,991;WARN;SupvisorsMapper.filter: identifier=ip-10-0-129-45:60000 invalid
2024-07-02 08:23:50,994;WARN;SupvisorsMapper.filter: identifier=ip-10-0-132-243:60000 invalid
2024-07-02 08:23:55,000;WARN;SupvisorsMapper.filter: identifier=ip-10-0-132-243:60000 invalid
2024-07-02 08:23:55,998;WARN;SupvisorsMapper.filter: identifier=ip-10-0-129-45:60000 invalid
2024-07-02 08:24:00,009;WARN;SupvisorsMapper.filter: identifier=ip-10-0-129-45:60000 invalid
2024-07-02 08:24:00,036;WARN;SupvisorsMapper.filter: identifier=ip-10-0-132-243:60000 invalid
2024-07-02 08:24:05,013;WARN;SupvisorsMapper.filter: identifier=ip-10-0-129-45:60000 invalid
2024-07-02 08:24:05,017;WARN;SupvisorsMapper.filter: identifier=ip-10-0-132-243:60000 invalid

It seems to be finding the instances but they are invalid?

**Comment by bartremans** [comment]
Hi,

The config-file
```
[inet_http_server]         ; inet (TCP) server disabled by default
port=:60000        ; ip_address:port specifier, *:port for all iface

[supervisord]
logfile=/home/ubuntu/ES.4/s3-bucket/supvisor_rules/supervisord.log ; main log file; default $CWD/supervisord.log
logfile_maxbytes=50MB        ; max main logfile bytes b4 rotation; default 50MB
logfile_backups=10           ; # of main logfile backups; 0 means none, default 10
loglevel=info                ; log level; default info; others: debug,warn,trace
pidfile=/tmp/supervisord.pid ; supervisord pidfile; default supervisord.pid
nodaemon=false               ; start in foreground if true; default false
silent=false                 ; no logs to stdout if true; default false
minfds=1024                  ; min. avail startup file descriptors; default 1024
minprocs=200                 ; min. avail process descriptors;default 200
identifier=S1
;childlogdir=/home/ubuntu/ES.4/s3-bucket/supvisor_rules/

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=http://localhost:60000 ; use an http:// url to specify an inet socket

;[eventlistener:zmq_client]
;command=sudo python3 -u /home/ubuntu/ES.4/s3-bucket/custom_modules/zmq_client.py
;events=EVENT
;buffer_size = 200

[include]
files = /home/ubuntu/ES.4/s3-bucket/supvisor_rules/*.ini

[rpcinterface:supvisors]
supervisor.rpcinterface_factory = supvisors.plugin:make_supvisors_rpcinterface
rules_files = /home/ubuntu/ES.4/s3-bucket/rules.xml
conciliation_strategy = RESTART
stereotypes = @SERVER
multicast_group = 239.0.0.1:5001
multicast_ttl = 10
core_identifiers = @SERVER


[ctlplugin:supvisors]
supervisor.ctl_factory = supvisors.supvisorsctl:make_supvisors_controller_plugin
```
They all log in the same file and have the same config-file

**Comment by julien6387** [comment]
Ok. First, Supervisor cannot cope with 3 instances logging into the same file. Actually, the last supervisor to start takes the ownership and is the only one to log in it.

I suggest you to update the `logfile` entry as follows:
    `logfile=/home/ubuntu/ES.4/s3-bucket/supvisor_rules/supervisord_%(host_node_name)s.log`
That will give a log file per Supervisor, named after the host name of the node.

And could you please retry and share all the log files ?

**Comment by julien6387** [comment]
Hi Bart,

I believe I've found the issue.
All your instances have the same identifier `S1` due to the option in the supervisord section of the configuration file:
```
[supervisord]
...
identifier=S1
```
When this option is set, and thus different from the default value `supervisor`, it **must** be unique per instance.
In your configuration, this is preventing the discovery mode to work because each node finds an existing identifier in itself.
I definitely have to make it more obvious in the logs.

Could you please retry with this option commented ?
Note that the filter warning should be displayed once anyway.

Then, if things are better, there are a few alternatives:
* leave it unset,
* start supervisord using the `-i` option and using a different parameter on every nodes,
* use a different config file per node.

I hope that it will help.

Regards,
Julien.

PS: I would also suggest you to use the 0.18.3 version, as it fixes a stability issue when the system is inactive for more than 30 minutes.

**Comment by bartremans** [comment]
```
ubuntu@ip-10-0-129-229:~$ supvisorsctl instance_status
Supervisor             Host             Port   State      Discovery  Load  Time      Counter  Processes  FSM             Discovery  Master                 Starting  Stopping
ip-10-0-129-229:60000  ip-10-0-129-229  60000  RUNNING    True       0%    07:20:55  336      ok         OPERATION       True       ip-10-0-129-229:60000  False     False
ip-10-0-129-45:60000   ip-10-0-129-45   60000  SILENT     False      0%    00:00:00  0        ok         OFF             False                             False     False
ip-10-0-132-243:60000  ip-10-0-132-243  60000  RUNNING    True       0%    07:20:55  336      ok         OPERATION       True       ip-10-0-129-229:60000  False     False
```

Yes, commenting the identifier argument did help! Thank you.
Still have one instance which is not responding but is using the same config-file so has to be something else.

Julien, thank you very much for your quick and professional support!

**Comment by julien6387** [comment]
Good news.
Feel free to share your logs again. Happy to help.
You can [mp me](mailto:julien.6387.dev@gmail.com) directly if it's more convenient to you.
