### ISSUE TITLE
Error: supvisors.plugin:make_supvisors_rpcinterface cannot be resolved within [rpcinterface:supvisors]

### ISSUE THREAD

**Issue by wukaka** [julien6387/supvisors#66]
hi:
   i'm running supvisors   on   Centos7.0, but that error has happened, and can u help
me troubleshoot this error? 

##supervisord.conf:

[inet_http_server]         ; inet (TCP) server disabled by default
port=:10000        ; (ip_address:port specifier, *:port for all iface)
;username=football              ; (default is no username (open server))
;password=k*@hu19k8aQ1               ; (default is no password (open server))

[supervisord]
logfile=/tmp/supervisord.log ; (main log file;default $CWD/supervisord.log)
logfile_maxbytes=500MB        ; (max main logfile bytes b4 rotation;default 50MB)
logfile_backups=10           ; (num of main logfile rotation backups;default 10)
loglevel=warn                ; (log level;default info; others: debug,warn,trace)
pidfile=/tmp/supervisord.pid ; (supervisord pidfile;default supervisord.pid)
nodaemon=false               ; (start in foreground if true;default false)
minfds=1024                  ; (min. avail startup file descriptors;default 1024)
minprocs=200                 ; (min. avail process descriptors;default 200)
[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface
[supervisorctl]
serverurl=http://localhost:10000 ; use an http:// url to specify an inet socket
[include]
files = /etc/supervisor/conf.d/*.conf
[supvisors]
address_list=47.92.152.87
deployment_file=/etc/supervisors/application.xml
auto_fence=false
internal_port=10001
event_port=10002
synchro_timeout=20
deployment_strategy=LESS_LOADED
conciliation_strategy=INFANTICIDE
stats_periods=5,60,600
stats_histo=100
logfile=/etc/supervisors/supvisors.log
logfile_maxbytes=50MB
logfile_backups=10
loglevel=info
[rpcinterface:supvisors]
supervisor.rpcinterface_factory = supvisors.plugin:make_supvisors_rpcinterface
[ctlplugin:supvisors]
supervisor.ctl_factory = supvisors.supvisorsctl:make_supvisors_controller_plugin

## applicaton.xml:

\<?xml version="1.0" encoding="UTF-8" standalone="no"?>
\<root>
   \
   \<application name="lunar_spider">
        \<start_sequence>3</start_sequence>
        \<stop_sequence>2</stop_sequence>
        \<program name="scrape_api_server">
            \<addresses>*</addresses>
            \<start_sequence>1</start_sequence>
            \<stop_sequence>2</stop_sequence>
            \<required>true</required>
            \<expected_loading>5</expected_loading>
        \</program>
     \</application>
\</root>

 thx!

**Comment by julien6387** [comment]
your XML is not valid.
there are missing ending tags for "addresses" and "required".

**Comment by julien6387** [comment]
however, this is not the cause of your problem.
it seems that your supvisors install is not in the python path.
can you import supvisors when using a simple python shell ?

**Comment by wukaka** [comment]
yes, there is no error when i run the supvisors client python shell. 
[root@iZ8vbesbzj30txz5t7fks4Z client]# pwd
/root/supvisors-0.1b5/supvisors/client
[root@iZ8vbesbzj30txz5t7fks4Z client]# python subscriber.py -p 10003
2017-07-19 19:05:52,889 INFO connecting EventSubscriber to Supvisors at tcp://127.0.0.1:10003
2017-07-19 19:05:52,889 INFO entering main loop
2017-07-19 19:06:02,900 INFO request to stop main loop
2017-07-19 19:06:02,901 WARN exiting main loop
[root@iZ8vbesbzj30txz5t7fks4Z client]#

**Comment by julien6387** [comment]
ok, correct me if I'm wrong.
it looks like you did not use the 'python setup.py install'.
you are just using an unzipped supvisors, aren't you ?
afterwards, you have expanded the PYTHONPATH to /root/supvisors-0.1b5

I assume that if you run the supervisord daemon manually in this environment, it should work.
however, if supervisord is automatically started at boot time, could you ensure that the PYTHONPATH is correctly set before supervisord is started ?

**Comment by julien6387** [comment]
For people reading this issue, shall you encounter this situation, please check that Supvisors is:
* either installed in the same python folder than supervisor (.../lib/python3.x/site-packages/)
* or reachable through the PYTHONPATH environment variable.

**Comment by julien6387** [comment]
For more information, please refer to the Supvisors [FAQ](https://supvisors.readthedocs.io/en/master/faq.html)
