### ISSUE TITLE
Collate CPU and mem usage over process group

### ISSUE THREAD

**Issue by mberglundmx** [julien6387/supvisors#89]
When 

```
stopasgroup=true
killasgroup=true
```

are set, the user probably want to see the CPU/mem utilization over the group, and not just the parent process.

Would this be possible to add?

**Comment by mberglundmx** [comment]
Silly me, I see it already is. I just confused that the % shown is total over all cores.

**Comment by julien6387** [comment]
np. if the % over all the cores is confusing you, please note that there is an option to control the IRIX mode used to display CPU load. See the option stats_irix_mode in:
https://supvisors.readthedocs.io/en/0.5/configuration.html#supvisors-section-values
